[profile.default]
src = "src"
out = "out"
libs = ["lib"]
build_info = true
sizes = true
optimizer = true
optimizer_runs = 21_000
gas_limit = "18446744073709551615" # u64::MAX

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"

[fuzz]
runs = 256
max_test_rejects = 65536
max_shrink_iters = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
